name: .NET Core 3.1 Functions

on:
  push:
    branches: [ main ]
    paths:
    - 'functions/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Restore, Build and Publish
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: fta-live-api    # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: '.' 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ./functions
      run: dotnet restore
    - name: Build
      working-directory: ./functions
      run: dotnet build --no-restore
    - name: Publish
      working-directory: ./functions
      run: dotnet publish -c Release -o 'myapp' 
    #- name: 'Run Azure webapp deploy action using publish profile credentials'
    #  if: github.ref == 'refs/heads/main'
    #  uses: azure/webapps-deploy@v2
    #  with: 
    #    app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
    #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
    #    package: './functions/myapp'
