name: .NET Core 3.1 Functions

on:
  push:
    branches: [ main ]
    paths:
    - 'functions/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Restore, Build and Publish
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: finddeal    # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: '.' 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ./functions/src/DealFinderAzFuncs
      run: dotnet restore
    - name: Build
      working-directory: ./functions/src/DealFinderAzFuncs
      run: dotnet build --no-restore
    - name: Publish
      working-directory: ./functions/src/DealFinderAzFuncs
      run: dotnet publish -c Release -o 'myapp' 
    - name: 'Deploy Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './functions/src/DealFinderAzFuncs/myapp'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
